services:
  server:
    build: .
    container_name: 'web'
    command: python3 start.py
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - practice
  postgres:
    image: postgres:15.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=tsarbirzzha
      - POSTGRES_USER=xorwise
      - POSTGRES_PASSWORD=2004m0804m
    expose:
      - 5432
    networks:
      - practice
  redis:
    image: redis
    ports:
      - "6379:6379"
  celery:
    build: .
    container_name: 'celery'
    command: celery -A worker.celery worker -B -l info
    networks:
      - practice
    depends_on:
      - server
      - redis

volumes:
  postgres_data:
networks:
  practice: